const Nightmare = require('nightmare');
const nightmare = Nightmare({ show: true, waitTimeout: 180000 });

nightmare
  .goto('https://demoapp.sandbox.aggreg8.hu')
  .wait('#share-account-button')
  .click('#share-account-button')
  .wait('#username')
  .type('#username', ['istvan.kadar.js@gmail.com'])
  .type('#password', ['asdf1234'])
  .click('#kc_input_button')
  .wait('mat-select[role=listbox]')
  .click('mat-select[role=listbox]')
  .click('#mat-option-7')
  .click('.mat-button-wrapper')
  .wait('#mainAccountNumber')
  .type('#mainAccountNumber', ['11034-20034278'])
  .type('#username', ['3535419'])
  .type('#password', ['London12'])
  .click('.mat-button-wrapper')
  .wait('.mat-button-wrapper')
  .click('.mat-button-wrapper')
  .wait('#account-list')
  .check('.mat-checkbox-layout')
  .wait('.mat-button-wrapper')
  .click('.mat-button-wrapper')
  .wait('.mat-button-wrapper')
  .click('.mat-button-wrapper')
  .wait('.striped')
  .goto('https://demoapp.sandbox.aggreg8.hu')
  .wait('#share-account-button')
  .click('#share-account-button')
  .wait('#username')
  .type('#username', ['istvan.kadar.js@gmail.com'])
  .type('#password', ['asdf1234'])
  .click('#kc_input_button')
  .wait('.mobil-large-button desktop-right-align desktop-small-button shareButton mat-raised-button')
  .click('.mobil-large-button desktop-right-align desktop-small-button shareButton mat-raised-button')
  .wait('.mediumDesktopBtn mat-raised-button')
  .click('.mediumDesktopBtn mat-raised-button')
  .wait('.material-icons')
  .end()
  .catch(error => {
    console.error('Error:', error);
  });
